In [ ]:
%tensorflow_version 2.x
import tensorflow as tf
print("Tensorflow version " + tf.__version__)

try:
  tpu = tf.distribute.cluster_resolver.TPUClusterResolver()  # TPU detection
  print('Running on TPU ', tpu.cluster_spec().as_dict()['worker'])
except ValueError:
  raise BaseException('ERROR: Not connected to a TPU runtime; please see the previous cell in this notebook for instructions!')

tf.config.experimental_connect_to_cluster(tpu)
tf.tpu.experimental.initialize_tpu_system(tpu)
tpu_strategy = tf.distribute.experimental.TPUStrategy(tpu)

Tensorflow version 2.4.1
Running on TPU  ['10.95.190.26:8470']
INFO:tensorflow:Initializing the TPU system: grpc://10.95.190.26:8470


INFO:tensorflow:Initializing the TPU system: grpc://10.95.190.26:8470


INFO:tensorflow:Clearing out eager caches


INFO:tensorflow:Clearing out eager caches


INFO:tensorflow:Finished initializing TPU system.


INFO:tensorflow:Finished initializing TPU system.


INFO:tensorflow:Found TPU system:


INFO:tensorflow:Found TPU system:


INFO:tensorflow:*** Num TPU Cores: 8


INFO:tensorflow:*** Num TPU Cores: 8


INFO:tensorflow:*** Num TPU Workers: 1


INFO:tensorflow:*** Num TPU Workers: 1


INFO:tensorflow:*** Num TPU Cores Per Worker: 8


INFO:tensorflow:*** Num TPU Cores Per Worker: 8


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving higgs_train.csv to higgs_train.csv


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
higgs = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Higgs/higgs_train.csv')
higgs.head()

DER_mass_MMC  DER_mass_transverse_met_lep  ...  PRI_met_sumet  Label
0      0.705457                     0.005221  ...       0.298439      0
1      0.559628                     0.420775  ...       0.487116      0
2      0.000000                     0.451817  ...       0.705405      0
3      0.514278                     0.205497  ...       0.629276      1
4      0.557471                     0.298073  ...       0.491825      1

[5 rows x 16 columns]

In [ ]:
higgs.shape

(754149, 16)

In [ ]:
X_train = higgs.drop('Label',axis = 1).values
Y_train = higgs['Label'].values

# **Modelling**

In [ ]:
from sklearn.svm import SVC 
#from sklearn.naive_bayes import BernoulliNB 
from sklearn import tree
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [ ]:
# Train LogisticRegression Model
LGR_Classifier = LogisticRegression(n_jobs=-1, random_state=0)
LGR_Classifier.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=-1, penalty='l2', random_state=0,
                   solver='lbfgs', tol=0.0001, verbose=0, warm_start=False)

In [ ]:
# Train RandomForestClassifier Model
RF_Classifier = RandomForestClassifier(criterion='entropy', n_jobs=-1, random_state=0)
RF_Classifier.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [ ]:
# Train KNeighborsClassifier Model
KNN_Classifier = KNeighborsClassifier(n_jobs=-1)
KNN_Classifier.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')

# Evaluating the **Models**

In [ ]:
from sklearn import metrics

models = []
models.append(('KNeighborsClassifier', KNN_Classifier))
models.append(('LogisticRegression', LGR_Classifier))
models.append(('RandomForest Classifier', RF_Classifier))



for i, v in models:
    scores = cross_val_score(v, X_train, Y_train, cv=10)
    accuracy = metrics.accuracy_score(Y_train, v.predict(X_train))
    confusion_matrix = metrics.confusion_matrix(Y_train, v.predict(X_train))
    classification = metrics.classification_report(Y_train, v.predict(X_train))
    print()
    print('============================== {} Model Evaluation =============================='.format(i))
    print()
    print ("Cross Validation Mean Score:" "\n", scores.mean())
    print()
    print ("Model Accuracy:" "\n", accuracy)
    print()
    print("Confusion matrix:" "\n", confusion_matrix)
    print()
    print("Classification report:" "\n", classification) 
    print()


============================== KNeighborsClassifier Model Evaluation ==============================

Cross Validation Mean Score:
 0.750545317404338

Model Accuracy:
 0.8283681341485568

Confusion matrix:
 [[289099  87797]
 [ 41639 335614]]

Classification report:
               precision    recall  f1-score   support

           0       0.87      0.77      0.82    376896
           1       0.79      0.89      0.84    377253

    accuracy                           0.83    754149
   macro avg       0.83      0.83      0.83    754149
weighted avg       0.83      0.83      0.83    754149



============================== LogisticRegression Model Evaluation ==============================

Cross Validation Mean Score:
 0.728303026662093

Model Accuracy:
 0.7287061310165498

Confusion matrix:
 [[250549 126347]
 [ 78249 299004]]

Classification report:
               precision    recall  f1-score   support

           0       0.76      0.66      0.71    376896
           1       0.70      0.

In [ ]:
from sklearn import metrics

models = []
#models.append(('KNeighborsClassifier', KNN_Classifier))
#models.append(('LogisticRegression', LGR_Classifier))
models.append(('RandomForest Classifier', RF_Classifier))



for i, v in models:
    scores = cross_val_score(v, X_train, Y_train, cv=10)
    accuracy = metrics.accuracy_score(Y_train, v.predict(X_train))
    confusion_matrix = metrics.confusion_matrix(Y_train, v.predict(X_train))
    classification = metrics.classification_report(Y_train, v.predict(X_train))
    print()
    print('============================== {} Model Evaluation =============================='.format(i))
    print()
    print ("Cross Validation Mean Score:" "\n", scores.mean())
    print()
    print ("Model Accuracy:" "\n", accuracy)
    print()
    print("Confusion matrix:" "\n", confusion_matrix)
    print()
    print("Classification report:" "\n", classification) 
    print()

In [ ]:
accuracy = metrics.accuracy_score(Y_train, RF_Classifier.predict(X_train))
print ("Model Accuracy:" "\n", accuracy)

Model Accuracy:
 0.9999880660187841


In [ ]:
test = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Higgs/higgs_test.csv')
test.head()

DER_mass_MMC  DER_mass_transverse_met_lep  ...  PRI_met_sumet  Label
0      0.362391                     0.050862  ...       0.533217      1
1      0.000000                     0.368750  ...       0.731896      0
2      0.286208                     0.183087  ...       0.875750      1
3      0.457508                     0.035842  ...       0.675285      1
4      0.000000                     0.569207  ...       0.479044      1

[5 rows x 16 columns]

In [ ]:
X_test = test.drop('Label',axis = 1).values
Y_test = test['Label'].values

In [ ]:
# Test accuracy
accuracy = metrics.accuracy_score(Y_test, RF_Classifier.predict(X_test))
print ("Model Accuracy:" "\n", accuracy)

Model Accuracy:
 0.8790248973568023


In [ ]:
confusion_matrix = metrics.confusion_matrix(Y_test, RF_Classifier.predict(X_test))
classification = metrics.classification_report(Y_test, RF_Classifier.predict(X_test))
print("Confusion matrix:" "\n", confusion_matrix)
print()
print("Classification report:" "\n", classification) 


Confusion matrix:
 [[136017  25765]
 [ 13335 148090]]

Classification report:
               precision    recall  f1-score   support

           0       0.91      0.84      0.87    161782
           1       0.85      0.92      0.88    161425

    accuracy                           0.88    323207
   macro avg       0.88      0.88      0.88    323207
weighted avg       0.88      0.88      0.88    323207



In [ ]:
from sklearn.externals import joblib
  
# Save the model as a pickle in a file
joblib.dump(RF_Classifier, 'Higgs_RF.pkl')

/usr/local/lib/python3.7/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


['Higgs_RF.pkl']

## Testing

In [ ]:
for i, v in models:
    accuracy = metrics.accuracy_score(Y_test, v.predict(X_test))
    confusion_matrix = metrics.confusion_matrix(Y_test, v.predict(X_test))
    classification = metrics.classification_report(Y_test, v.predict(X_test))
    print()
    print('============================== {} Model Test Results =============================='.format(i))
    print()
    print ("Model Accuracy:" "\n", accuracy)
    print()
    print("Confusion matrix:" "\n", confusion_matrix)
    print()
    print("Classification report:" "\n", classification) 
    print()


============================== KNeighborsClassifier Model Test Results ==============================

Model Accuracy:
 0.7519422537259404

Confusion matrix:
 [[111185  50597]
 [ 29577 131848]]

Classification report:
               precision    recall  f1-score   support

           0       0.79      0.69      0.74    161782
           1       0.72      0.82      0.77    161425

    accuracy                           0.75    323207
   macro avg       0.76      0.75      0.75    323207
weighted avg       0.76      0.75      0.75    323207



============================== LogisticRegression Model Test Results ==============================

Model Accuracy:
 0.7276636954026366

Confusion matrix:
 [[107524  54258]
 [ 33763 127662]]

Classification report:
               precision    recall  f1-score   support

           0       0.76      0.66      0.71    161782
           1       0.70      0.79      0.74    161425

    accuracy                           0.73    323207
   macro avg    

In [ ]:
import pickle
# save the model to disk
filename = 'Random_Higgs_model.sav'
pickle.dump(RF_Classifier, open(filename, 'wb'))